const BACKGROUND_COLOR = 'rgb(255, 255, 255)';
const ON_BACKGROUND_COLOR = 'rgb(0, 0, 0)';
const SURFACE_COLOR = 'rgb(236, 239, 244)';
const ON_SURFACE_COLOR = 'rgb(194, 201, 214)';
const PRIMARY_COLOR = 'rgb(84, 88, 247)';
const PRIMARY_VARIANT_ONE_COLOR = 'rgb(66, 134, 245)';
const ON_PRIMARY_COLOR = 'rgb(255, 255, 255)';
const SECONDARY_COLOR = 'rgb(255, 255, 255)';
const ON_SECONDARY_COLOR = 'rgb(194, 201, 214)';
const TEXT_FONT_BOLD = 'SF-Pro-Text-Bold';
const TEXT_FONT_BOLD_ITALIC = 'SF-Pro-Text-BoldItalic';
const TEXT_FONT_HEAVY = 'SF-Pro-Text-Heavy';
const TEXT_FONT_HEAVY_ITALIC = 'SF-Pro-Text-HeavyItalic';
const TEXT_FONT_LIGHT = 'SF-Pro-Text-Light';
const TEXT_FONT_LIGHT_ITALIC = 'SF-Pro-Text-LightItalic';
const TEXT_FONT_MEDIUM = 'SF-Pro-Text-Medium';
const TEXT_FONT_MEDIUM_ITALIC = 'SF-Pro-Text-MediumItalic';
const TEXT_FONT_REGULAR = 'SF-Pro-Text-Regular';
const TEXT_FONT_REGULAR_ITALIC = 'SF-Pro-Text-RegularItalic';
const TEXT_FONT_SEMIBOLD = 'SF-Pro-Text-Semibold';
const TEXT_FONT_SEMIBOLD_ITALIC = 'SF-Pro-Text-SemiboldItalic';
const PARAGRAPH_FONT_SIZE = 18;
const H1_FONT_SIZE = 24;
const H2_FONT_SIZE = 22;
const H3_FONT_SIZE = 20;
const SUBHEADING_FONT_SIZE = 16;
const SUBTEXT_FONT_SIZE = 14;

export {
  BACKGROUND_COLOR,
  ON_BACKGROUND_COLOR,
  SURFACE_COLOR,
  ON_SURFACE_COLOR,
  PRIMARY_COLOR,
  PRIMARY_VARIANT_ONE_COLOR,
  ON_PRIMARY_COLOR,
  SECONDARY_COLOR,
  ON_SECONDARY_COLOR,
  TEXT_FONT_BOLD,
  TEXT_FONT_BOLD_ITALIC,
  TEXT_FONT_HEAVY,
  TEXT_FONT_HEAVY_ITALIC,
  TEXT_FONT_LIGHT,
  TEXT_FONT_LIGHT_ITALIC,
  TEXT_FONT_MEDIUM,
  TEXT_FONT_MEDIUM_ITALIC,
  TEXT_FONT_REGULAR,
  TEXT_FONT_REGULAR_ITALIC,
  TEXT_FONT_SEMIBOLD,
  TEXT_FONT_SEMIBOLD_ITALIC,
  PARAGRAPH_FONT_SIZE,
  H1_FONT_SIZE,
  H2_FONT_SIZE,
  H3_FONT_SIZE,
  SUBHEADING_FONT_SIZE,
  SUBTEXT_FONT_SIZE,
}