const MARGIN_TOP_COVER_VIEW = 10;
const MARGIN_BOTTOM_COVER_VIEW = 10;
const MARGIN_LEFT_BETWEEN_AVATAR_AND_CONTENT = 6;
const MARGIN_TOP_CONTENT_VIEW = 6;
const MARGIN_TOP_MILESTONE = 3;
const COVER_ICON_VIEW_WIDTH = 20;
const SWIPE_START_MIN_DISTANCE = 70;

export {
    MARGIN_TOP_COVER_VIEW,
    MARGIN_BOTTOM_COVER_VIEW,
    MARGIN_LEFT_BETWEEN_AVATAR_AND_CONTENT,
    MARGIN_TOP_CONTENT_VIEW,
    MARGIN_TOP_MILESTONE,
    COVER_ICON_VIEW_WIDTH,
    SWIPE_START_MIN_DISTANCE,
}